language: node_js
node_js:
  - "7"
script:
  - npm install yarn
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  target-branch: gh-pages
  keep-history: true
  on:
    branch: master