language: node_js
node_js:
  - "7"
script:
  - git config --global user.email $email
  - git config --global user.password $github_token
  - npm install yarn
  - yarn add gh-pages
  - npm run build
  - gh-pages -d build