language: node_js
node_js:
  - "7"
script:
  - git config --global user.email publish@travis.github
  - git config --global user.name "Travis"
  - npm install yarn
  - yarn add gh-pages
  - npm run build
  - gh-pages -d build